version: '3.2'
services:
  backend1:
      image: bomeara/datelifedocker
  backend2:
      image: bomeara/datelifedocker
  backend3:
      image: bomeara/datelifedocker
  backend4:
      image: bomeara/datelifedocker
  backend5:
      image: bomeara/datelifedocker
  backend6:
      image: bomeara/datelifedocker
  backend7:
      image: bomeara/datelifedocker
  backend8:
      image: bomeara/datelifedocker
  backend9:
      image: bomeara/datelifedocker
  backend10:
      image: bomeara/datelifedocker
  loadbalancer:
      build: .
      tty: true
      links:
          - backend1
          - backend2
          - backend3
          - backend4
          - backend5
          - backend6
          - backend7
          - backend8
          - backend9
          - backend10

      ports:
          - '80:80'
